export const estudios = [
    {   //Tecnólogo en Análisis y Desarrollo de SI
        id: 1,
        idEstudios: 1,
        badgeWarningEstudios: "Educación Formal",
        badgePrimaryEstudios: "Abril 2019 - Diciembre 2020",
        programaEstudios: "Tecnólogo en Análisis y Desarrollo de SI",
        institucionEstudios: "Servicio Nacional de Aprendizaje SENA",
    },
    {   //Técnico en programación de Software
        id: 2,
        idEstudios: 2,
        badgeWarningEstudios: "Educación Formal",
        badgePrimaryEstudios: "Abril 2017 - Noviembre 2018",
        programaEstudios: "Técnico en programación de Software",
        institucionEstudios: "Servicio Nacional de Aprendizaje SENA",
    },
    {   //Colegio General Santander
        id: 3,
        idEstudios: 3,
        badgeWarningEstudios: "Educación Formal",
        badgePrimaryEstudios: "2007 - 2018",
        programaEstudios: "Bachiller Académico",
        institucionEstudios: "Colegio General Santander",
    },
    {   //Desarrollo Front-End con ReactJS
        id: 4,
        idEstudios: 4,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Junio 2022 - Actualmente",
        programaEstudios: "Desarrollo Front-End con ReactJS",
        institucionEstudios: "Fundación Maria Luisa de Moreno - LiveVox de Colombia SAS",
    },
    {   //Desarrollador Back-End
        id: 5,
        idEstudios: 5,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Febrero 2022 - Febrero 2022",
        programaEstudios: "Desarrollador Back-End",
        institucionEstudios: "Capacítate para el Empleo - Fundación Carlos Slim",
    },
    {   //Desarrollador Front-End
        id: 6,
        idEstudios: 6,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Enero 2022 - Enero 2022",
        programaEstudios: "Desarrollador Front-End",
        institucionEstudios: "Capacítate para el Empleo - Fundación Carlos Slim",
    },
    {   //Curso de Integridad y Lenguaje Claro
        id: 7,
        idEstudios: 7,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Enero 2022 - Enero 2022",
        programaEstudios: "Curso de Integridad y Lenguaje Claro",
        institucionEstudios: "Función Pública",
    },
    {   //programaEstudiosdor Orientado a Objetos
        id: 8,
        idEstudios: 8,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Diciembre 2021 - Diciembre 2021",
        programaEstudios: "programador Orientado a Objetos",
        institucionEstudios: "Capacítate para el Empleo - Fundación Carlos Slim",
    },
    {   //Administrador de Servidores
        id: 9,
        idEstudios: 9,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Diciembre 2021 - Diciembre 2021",
        programaEstudios: "Administrador de Servidores",
        institucionEstudios: "Capacítate para el Empleo - Fundación Carlos Slim",
    },
    {   //Curador de Datos
        id: 10,
        idEstudios: 10,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Diciembre 2021 - Diciembre 2021",
        programaEstudios: "Curador de Datos",
        institucionEstudios: "Capacítate para el Empleo - Fundación Carlos Slim",
    },
    {   //Administrador de Base de Datos
        id: 11,
        idEstudios: 11,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Diciembre 2021 - Diciembre 2021",
        programaEstudios: "Administrador de Base de Datos",
        institucionEstudios: "Capacítate para el Empleo - Fundación Carlos Slim",
    },
    {   //Disciplina en el Trabajo
        id: 12,
        idEstudios: 12,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Septiembre 2021 - Septiembre 2021",
        programaEstudios: "Disciplina en el Trabajo",
        institucionEstudios: "Capacítate para el Empleo - Fundación Carlos Slim",
    },
    {   //Diplomado en Desarrollo de Aplicaciones Web de Misión TIC 2022
        id: 13,
        idEstudios: 13,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Abril 2021 - Diciembre 2021",
        programaEstudios: "Diplomado en Desarrollo de Aplicaciones Web de Misión TIC 2022",
        institucionEstudios: "Universidad Tecnológica de Pereira",
    },
    {   //Administración de Sistemas y Servicios de Infraestructura en TI
        id: 14,
        idEstudios: 14,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Abril 2021 - Abril 2021",
        programaEstudios: "Administración de Sistemas y Servicios de Infraestructura en TI",
        institucionEstudios: "Google Coursera",
    },
    {   //SeguridEstudiosad Informática defensa contra las Artes
        id: 15,
        idEstudios: 15,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Abril 2021 - Abril 2021",
        programaEstudios: "Seguridad Informática defensa contra las Artes",
        institucionEstudios: "Google Coursera",
    },
    {   //Sistemas Operativos y Convertirse en un Usuario Avanzado
        id: 16,
        idEstudios: 16,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Marzo 2021 - Marzo 2021",
        programaEstudios: "Sistemas Operativos y Convertirse en un Usuario Avanzado",
        institucionEstudios: "Google Coursera",
    },
    {   //Aspectos Básicos de la Asistencia Técnica
        id: 17,
        idEstudios: 17,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Marzo 2021 - Marzo 2021",
        programaEstudios: "Aspectos Básicos de la Asistencia Técnica",
        institucionEstudios: "Google Coursera",
    },
    {   //Certificado Profesional en Soporte de TI
        id: 18,
        idEstudios: 18,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Enero 2021 - Abril 2021",
        programaEstudios: "Certificado Profesional en Soporte de TI",
        institucionEstudios: "Universidad de Cafam - IYF - Google",
    },
    {   //Los Bits y Bytes de las Redes Informáticas
        id: 19,
        idEstudios: 19,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Febrero 2021 - Febrero 2021",
        programaEstudios: "Los Bits y Bytes de las Redes Informáticas",
        institucionEstudios: "Google Coursera",
    },
    {   //Python Data Structures
        id: 20,
        idEstudios: 20,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Diciembre 2020 - Diciembre 2020",
        programaEstudios: "Python Data Structures",
        institucionEstudios: "Universidad de Michigan - Coursera",
    },
    {   //Using Python to Access Web Data
        id: 21,
        idEstudios: 21,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Diciembre 2020 - Diciembre 2020",
        programaEstudios: "Using Python to Access Web Data",
        institucionEstudios: "Universidad de Michigan - Coursera",
    },
    {   //Diplomado en Escuela de Nuevos liderazgos en Cultura Democrática
        id: 22,
        idEstudios: 22,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Agosto 2020 - Octubre 2020",
        programaEstudios: "Diplomado en Escuela de Nuevos liderazgos en Cultura Democrática",
        institucionEstudios: "Escuela Superior de Administración Pública",
    },
    {   //Programming for Everybody 
        id: 23,
        idEstudios: 23,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Noviembre 2020 - Diciembre 2020",
        programaEstudios: "Programming for Everybody ",
        institucionEstudios: "Universidad de Michigan - Coursera",
    },
    {   //Diplomado Virtual en Cooperación, Gestión de Proyectos y Financiación para el Desarrollo
        id: 24,
        idEstudios: 24,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Agosto 2020 - Octubre 2020",
        programaEstudios: "Diplomado Virtual en Cooperación, Gestión de Proyectos y Financiación para el Desarrollo",
        institucionEstudios: "Universidad del Externado",
    },
    {   //Mejoramiento Continuo
        id: 25,
        idEstudios: 25,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Mayo 2020 - Mayo 2020",
        programaEstudios: "Mejoramiento Continuo",
        institucionEstudios: "Ubits",
    },
    {   //Proyecto de Vida
        id: 26,
        idEstudios: 26,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Mayo 2020 - Mayo 2020",
        programaEstudios: "Proyecto de Vida",
        institucionEstudios: "Ubits",
    },
    {   //Diplomado en Políticas Públicas
        id: 27,
        idEstudios: 27,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Agosto 2021 - Noviembre 2021",
        programaEstudios: "Diplomado en Políticas Públicas",
        institucionEstudios: "Escuela Superior de Administración Pública",
    },
    {   //Diplomado en Marketing y Análisis Político
        id: 28,
        idEstudios: 28,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Agosto 2021 - Noviembre 2021",
        programaEstudios: "Diplomado en Marketing y Análisis Político",
        institucionEstudios: "Universidad Sergio Arboleda",
    },
    {   //Capstone: Retrieving, Processing and Visualizing Data With Python 
        id: 29,
        idEstudios: 29,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Noviembre 2020 - Diciembre 2020",
        programaEstudios: "Capstone: Retrieving, Processing and Visualizing Data With Python ",
        institucionEstudios: "Universidad de Michigan - Coursera",
    },
    {   //Taller de participación ciudadana pública y formación política para Jóvenes
        id: 30,
        idEstudios: 30,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Julio 2020 - Agosto 2020",
        programaEstudios: "Taller de participación ciudadana pública y formación política para Jóvenes",
        institucionEstudios: "Escuela Superior de Administración Pública",
    },
    {   //Bootcamp de Lenguajes de programación DataScience
        id: 31,
        idEstudios: 31,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Agosto 2020 - Noviembre 2020",
        programaEstudios: "Bootcamp de Lenguajes de programación DataScience",
        institucionEstudios: "Keycode",
    },
    {   //English Dot Works 2
        id: 32,
        idEstudios: 32,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Agosto 2019 - Septiembre 2019",
        programaEstudios: "English Dot Works 2",
        institucionEstudios: "Servicio Nacional de Aprendizaje SENA",
    },
    {   //English Dot Works Begginners
        id: 33,
        idEstudios: 33,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Mayo 2018 - Junio 2018",
        programaEstudios: "English Dot Works Begginners",
        institucionEstudios: "Servicio Nacional de Aprendizaje SENA",
    },
    {   //English Dot Works 1
        id: 34,
        idEstudios: 34,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Mayo 2017- Junio 2016",
        programaEstudios: "English Dot Works 1",
        institucionEstudios: "Servicio Nacional de Aprendizaje SENA",
    },
    {   //Siete habilidEstudiosades de un buen líder
        id: 35,
        idEstudios: 35,
        badgeWarningEstudios: "Educación Informal",
        badgePrimaryEstudios: "Mayo 2020 - Mayo 2020",
        programaEstudios: "Siete habilidades de un buen líder",
        institucionEstudios: "Ubits",
    },
]