export const experiencia = [
    {
        id: 1,
        cardImgTopExperiencia:"https://bit.ly/3qO6SDG",
        badgeInfoExperiencia:"Sector público",
        badgePrimaryExperiencia: "Diciembre 2021 - Actualmente",
        cargoExperiencia: "Técnico I - Desarrolladora",
        empresaExperiencia: "Caja Honor",
        actividad1Experiencia:"Desarrollar scripts de bases de datos para solucionar tickets.",
        actividad2Experiencia:"Brindar soporte en el aplicativo CORE de la compañía.",
        actividad3Experiencia:"Pruebas en el aplicativo CORE de la compañía.",
        actividad4Experiencia:"Creación de bots para la automatización de los procesos en seguir el paso para la exportación de informes.",
    },
    {
        id: 2,
        cardImgTopExperiencia:"https://cutt.ly/RVpT5H8",
        badgeInfoExperiencia:"Sector privado",
        badgePrimaryExperiencia: "Marzo 2021 - Diciembre 2021",
        cargoExperiencia: "Desarrolladora Junior",
        empresaExperiencia: "Minos IT",
        actividad1Experiencia:"Desarrollar scripts de bases de datos.",
        actividad2Experiencia:"Creación de manuales de usuario, pruebas y funcionales, creación de presentaciones para reuniones de metodología SCRUM y cronogramas de GANT.",
        actividad3Experiencia:"Brindar soporte a aplicativos creados por la compañía.",
        actividad4Experiencia:"Realizar pruebas funcionales para los aplicativos.",
    },
    {
        id: 3,
        cardImgTopExperiencia:"https://grupomeiko.com/wp-content/uploads/2019/12/Meiko-Brand-Guidelines.jpg",
        badgeInfoExperiencia:"Sector privado",
        badgePrimaryExperiencia: "Abril 2020 - Octubre 2020",
        cargoExperiencia: "Aprendiz SENA",
        empresaExperiencia: "Grupo Meiko S.A.S",
        actividad1Experiencia:"Desarrollar servicios.",
        actividad2Experiencia:"Uso de tecnologías Docker, Jenkins y GIT.",
        actividad3Experiencia:"Aplicación de buenas prácticas para el proceso de desarrollo.",
        actividad4Experiencia:"Creación y soporte a páginas WEB.",
    }
]